from typing import Any

class Headers:
    def __init__(self, init: dict[str, str] | list[list[str]] | None = None) -> None: ...
    def append(self, name: str, value: str) -> None: ...
    def delete(self, name: str) -> None: ...
    def get(self, name: str) -> str | None: ...
    def has(self, name: str) -> bool: ...
    def set(self, name: str, value: str) -> None: ...
    def entries(self) -> Any: ...
    def keys(self) -> Any: ...
    def values(self) -> Any: ...

class Request:
    def __init__(self, input: str, init: dict[str, Any] | None = None) -> None: ...
    @property
    def url(self) -> str: ...
    @property
    def method(self) -> str: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def body(self) -> Any: ...

class Response:
    def __init__(self, body: Any | None = None, init: dict[str, Any] | None = None) -> None: ...
    @property
    def status(self) -> int: ...
    @property
    def ok(self) -> bool: ...
    @property
    def statusText(self) -> str: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def body(self) -> Any: ...
    @classmethod
    def json(cls, data: Any, init: dict[str, Any] | None = None) -> Response: ...
    @classmethod
    def new(cls, body: Any | None = None, init: dict[str, Any] | None = None) -> Response: ...

class Object:
    @staticmethod
    def fromEntries(entries: Any) -> Any: ...

async def fetch(input: str | Request, init: dict[str, Any] | None = None) -> Response: ...
